name: Build 

on: [push]

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        example:
          - "examples/arduino-blink"
          - "examples/arduino-external-libs"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
      - name: Build examples
        run: |
          pio run -d ${{ matrix.example }}

      - name: Upload bin
        uses: actions/upload-artifact@v3
        with:
            name: ${{matrix.example}}.bin
            path: ./out
