name: Build 

on: [push]

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        example:
          - "examples/arduino-blink"
          - "examples/arduino-external-libs"
        var: [arduino-blink arduino-external-libs]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
      - name: Build examples
        run: |
          pio run -d ${{ matrix.example }}

      - name: Upload bin
        uses: actions/upload-artifact@v3
        with:
            name: ${{matrix.var}}.uf2
            path: ${{matrix.example}}/.pio/build/pico/firmware.uf2

      - name: Upload artifacts
        uses: lumo-systems/s3-upload-github-action@master
        env:
          FILE: .pio/build/${{ matrix.target }}/poseidon_${{ matrix.var }}.bin
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: poseidon-builds
          S3_KEY: ${{ matrix.var }}/${{ env.TIMESTAMP }}.bin

